# An Exploration of the numpy.random package in Python
## Submission Assignment for Programming for Data Analysis
#### Gerry Donnelly November 2021

The purpose of this assignment is to explore the numpy.random package in Python. This exploration will address the following areas:
1. Explain the overall purpose of the package. 
2. Explain the use of the “Simple random data” and “Permutations” functions. 
3. Explain the use and purpose of at least five “Distributions” functions. 
4. Explain the use of seeds in generating pseudorandom numbers.

### Section 1 - Overall Purpose of the numpy.random package.

- what is a random number
https://mathworld.wolfram.com/RandomNumber.html
A random number is a number chosen as if by chance from some specified distribution such that selection of a large set of these numbers reproduces the underlying distribution. Almost always, such numbers are also required to be independent, so that there are no correlations between successive numbers. 

- what is a pseudorandom number
A sequence of numbers satisfying one or more statistical tests for randomness but produced by a definite mathematical procedure. Pseudorandom means it's produced by an algorithm that generates a series of bits that appear unpredictable, but in fact are computed from an algorithm.

- what is difference
It is very difficult to produce true randomness. Computers are by definition deterministic, i.e. they are designed to have predetermined outputs so various techniques, both hardware and software are used to produce pseudorandom numbers. 

- why are they important.
Random number generation is very important in the areas of cryptography, science, ganbling, statistics.  
- random numbers in computing.
https://www.howtogeek.com/183051/htg-explains-how-computers-generate-random-numbers/
Computers typically use an algorithim or program with some seed value to generate numbers that appear random but in fact are not truly random, i.e. pseudo random numbers. 

- Random numbers in data analysis

- what is numpy

https://numpy.org/doc/stable/user/whatisnumpy.html

Numpy is the primary Python library for working with arrays and matrices and provides significantly faster (x50) manipulation of these than using Python lists. Numpy is designed to store its arrays in continuous memory so programs and processes can be carried out very efficiently. 
NumPy an array object of type ***ndarray*** . Numpy creates n-dimensional arrays of homogeneous data types, usually numnbers but can be strings, with the dimensions of the array called ***axes.***

- what is numpy.random
https://numpy.org/doc/stable/reference/random/index.html
As stated above computers are designed to be deterministic, i.e. they produce fixed and repeatable outputs so the generation of random numbers is programatically produced using algorithims to create pseudorandon numbers, i.e. to give the appearance of randomness. In general these numbers are sufficient for most tasks in analytics with true randon mumbers generally needed for security, for example encryption keys. 

Numpys randon numbers are produced by a combination of a BitGenerator to create random number sequences and a Generator to sample from these numbers using statistical distributions, e.g. Normal, Binomial, Poisson.  These distributions will be described in section 3 of the assignment. 

- examples of some simple random plots


In [11]:
# Numpy.random is initiiated as follows:
import numpy as np
from numpy import random

In [71]:
# rand generates an array of positive random floating point numbers in the range 0 to 1, e.g. this produces 6 random numbers in a single array.
x = random.rand(6)
print('This is a single array:\n',x)

This is a single array:
 [0.23990884 0.66923846 0.01265323 0.72533616 0.40396227 0.74303454]


In [69]:
# rand also generates multi-dimensional arrays by specifying the optional array parameter, e.g. below produces 6 rows of 3 floats per row, a (6x3 array).
x = random.rand(6,3)
print('This is a 6x3 array:\n',x)

This is a 6x3 array:
 [[0.35172612 0.11276622 0.40936513]
 [0.9565635  0.27675688 0.86616963]
 [0.86636129 0.33163855 0.16627187]
 [0.52469412 0.65792182 0.29556233]
 [0.46416573 0.64697301 0.61816034]
 [0.33091937 0.71136408 0.9198335 ]]


In [73]:
# randint produces random integers from the uniform distribution, e.g. below produces a single array of 10 random numbers from the range 1 - 6, could be used to simulate dice throws. 
rint = np.random.randint(1,7,size=(10))
print('This is a single array of random integers:\n',rint)

This is a single array of random integers:
 [4 2 6 3 4 2 4 1 3 6]


In [74]:
# randint can also produce 2D arrays, e.g. below produces a 2D array of 3 rows with 10 random numbers in each row from the range 1 - 6, could be used to simulate dice throws. 
rint1 = np.random.randint(1,7,size=(3,10))
print('This is a 2D array of 3 rows of 10 random integers:\n',rint1)

This is a 2D array of 3 rows of 10 random integers:
 [[1 6 4 6 6 4 1 2 5 3]
 [6 1 5 1 3 1 4 2 4 2]
 [2 6 4 6 6 3 6 5 2 1]]


In [95]:
#Using the random choice() method allows for a random selction from that a 1D array, using an array of strings below to show that strings as well as numbers can be used in the arrays.
rchstr = ("numpy","random", "assignment", "choice", "method")
print('This is a random 3x5 array from an array of strings:\n',np.random.choice(rch, size=(3,5)))

This is a random 3x5 array selection from an array of strings:
 [['choice' 'assignment' 'random' 'choice' 'choice']
 ['assignment' 'assignment' 'assignment' 'random' 'numpy']
 ['choice' 'method' 'assignment' 'random' 'method']]


In [99]:
#Using the random choice() method allows for a random selction from that a 1D array, using an array of strings below to show that strings as well as numbers can be used in the arrays.
rchint = (1,2,3,4,5,6)
print('This is a random 3x5 array of integers from an array of numbers:\n',np.random.choice(rchint, size=(3,5)))

This is a random 3x5 array of integers from an array of numbers:
 [[6 2 2 1 6]
 [4 6 6 5 1]
 [5 1 6 2 1]]


### Section 2 - Description and Use of Simple Random Data and Permutations Functions

- What is simple random data
    - uses
    - examples

- what are permutations
    - uses
    - examples

### Section 3 - Exploration of 5 Distribution functions.

#### Distribution 1
- description
- uses
- examples

#### Distribution 2
- description
- uses
- examples

#### Distribution 3
- description
- uses
- examples

#### Distribution 3
- description
- uses
- examples

#### Distribution 3
- description
- uses
- examples

### Section 4
Use of Seeds
- What are seeds
- why are they used
- what does numpy.random use as default
examples

### Section 4 - Use of Seeds to Generate PseudoRandom Numbers.

## Websites

## References