# An Exploration of the numpy.random package in Python
## Submission Assignment for Programming for Data Analysis
#### Gerry Donnelly November 2021

The purpose of this assignment is to explore the numpy.random package in Python. This exploration will address the following areas:
1. Explain the overall purpose of the package. 
2. Explain the use of the “Simple random data” and “Permutations” functions. 
3. Explain the use and purpose of at least five “Distributions” functions. 
4. Explain the use of seeds in generating pseudorandom numbers.

### Section 1 - Overall Purpose of the numpy.random package.

#### What is a random number
*https://mathworld.wolfram.com/RandomNumber.html*

A random number is a number chosen as if by chance from some specified distribution such that selection of a large set of these numbers reproduces the underlying distribution. Almost always, such numbers are also required to be independent, so that there are no correlations between successive numbers. 

#### What is a pseudorandom number

A sequence of numbers satisfying one or more statistical tests for randomness but produced by a definite mathematical procedure. Pseudorandom means it's produced by an algorithm that generates a series of bits that appear unpredictable, but in fact are computed from an algorithm.

#### What is difference between both. 

It is very difficult to produce true randomness. Computers are by definition deterministic, i.e. they are designed to have predetermined outputs so various techniques, both hardware and software are used to produce pseudorandom numbers. 

#### Why are they important.

Random number generation is very important in the areas of cryptography, science, ganbling, statistics.  
- random numbers in computing.

*https://www.howtogeek.com/183051/htg-explains-how-computers-generate-random-numbers/*

Computers typically use an algorithim or program with some seed value to generate numbers that appear random but in fact are not truly random, i.e. pseudo random numbers. 

### Random numbers in data analysis

#### What is numpy

*https://numpy.org/doc/stable/user/whatisnumpy.html*

Numpy is the primary Python package for working with arrays and matrices and provides significantly faster (x50) manipulation of these than using Python lists. Numpy is designed to store its arrays in continuous memory so programs and processes can be carried out very efficiently. 
NumPy is an array object of type ***ndarray*** . Numpy creates n-dimensional arrays of homogeneous data types, usually numnbers but can be strings, with the dimensions of the array called ***axes.***

#### What is numpy.random

*https://numpy.org/doc/stable/reference/random/index.html*

As stated above computers are designed to be deterministic, i.e. they produce fixed and repeatable outputs so the generation of random numbers is programatically produced using algorithims to create pseudorandon numbers, i.e. to give the appearance of randomness. In general these numbers are sufficient for most tasks in analytics with true randon mumbers generally needed for security, for example encryption keys. 

Numpys random numbers are produced by a combination of a BitGenerator to create random number sequences and a Generator to sample from these numbers using statistical distributions, e.g. Normal, Binomial, Poisson.  These distributions will be described in section 3 of the assignment. 

### Section 2 - Description and Use of Simple Random Data and Permutations Functions
#### 2.1 Simple Random Data
***

In [1]:
# Numpy.random is initiiated as follows, import the random package. 
import numpy as np
from numpy import random

Below are some simple examples of random number generation using **rand**. 

*[Link here to **numpy.random.rand**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)*

Ex.1 This generates an array of positive random floating point numbers in the range 0 to 1, e.g. the code below  produces 6 random floats in a single array.<br>
Ex.2 This code generates a simple 6x3 array, i.e. 6 sets of 3 random floats.  

In [2]:
# Ex.1 Use of rand to produce 6 random numbers in the range 0 to 1.
x = random.rand(6)
print('This is a single array:\n',x)

This is a single array:
 [0.45279707 0.43566694 0.01568116 0.3147793  0.25047752 0.20251983]


In [3]:
# Ex.2 rand also generates multi-dimensional arrays by specifying the optional array parameter, e.g. below produces 6 rows of 3 floats per row, a (6x3 array).
x = random.rand(6,3)
print('This is a 6x3 array:\n',x)

This is a 6x3 array:
 [[0.88893791 0.44716531 0.209191  ]
 [0.86199872 0.7170191  0.09504618]
 [0.74409857 0.23982076 0.32969226]
 [0.51757909 0.89773137 0.42231503]
 [0.70567498 0.55386728 0.76794044]
 [0.05901489 0.48677022 0.75516577]]


Below are further examples of random number generation using **randint**. This produces random integers, you can specify the range and the number of integers you want in the output. 

*[Link here to **numpy.random.randint**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)*

Ex.1 This generates an array of 10 positive random integers in the range 0 to 7. (note when specifying a range from x to y the output will produce numbers in the range x to y-1).<br>
Ex.2 This code generates a simple 2d array of  i.e. 6 sets of 3 random floats.  

In [4]:
# Ex. 1 randint produces random integers from the uniform distribution, e.g. below produces a single array of 10 random numbers from the range 1 - 6, could be used to simulate dice throws. 
rint = np.random.randint(0,7,size=(10))
print('This is a single array of random integers:\n',rint)

This is a single array of random integers:
 [3 6 6 5 1 6 2 3 6 2]


In [5]:
# Ex.2 randint can also produce 2D arrays, e.g. below produces a 2D array of 3 rows with 10 random numbers in each row from the range 1 - 6, could be used to simulate dice throws. 
rint1 = np.random.randint(1,7,size=(3,10))
print('This is a 2D array of 3 rows of 10 random integers:\n',rint1)

This is a 2D array of 3 rows of 10 random integers:
 [[2 2 6 2 4 4 1 1 6 5]
 [2 3 2 4 5 2 4 4 2 5]
 [1 3 1 1 5 1 3 3 4 6]]


Using the random choice() method allows for a random selection from a 1D array. 

*[Link here to **numpy.random.choice**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html)*

In the example below using an array of strings to demonstrate that strings as well as numbers can be used in the arrays.

In [6]:
# Demonstrating that strings can be used to produce random outputs. 
rchstr = ("numpy","random", "assignment", "choice", "method")
print('This is a random 3x5 array from an array of strings:\n',np.random.choice(rchstr, size=(5,5)))

This is a random 3x5 array from an array of strings:
 [['random' 'choice' 'numpy' 'choice' 'numpy']
 ['method' 'choice' 'numpy' 'assignment' 'method']
 ['method' 'random' 'numpy' 'method' 'numpy']
 ['method' 'choice' 'numpy' 'numpy' 'method']
 ['assignment' 'numpy' 'method' 'choice' 'random']]


In [7]:
#Using the random choice() method allows for a random selction from that a 3 x 5 array. array.
rchint = (1,2,3,4,5,6)
print('This is a random 3x5 array of integers from an array of numbers:\n',np.random.choice(rchint, size=(3,5)))

This is a random 3x5 array of integers from an array of numbers:
 [[6 6 4 4 1]
 [5 2 5 5 2]
 [1 5 5 3 3]]


#### 2.2 Permutations
***

A permutation refers to how elements in an array are arranged and numpy provides 2 methods, **shuffle()** and **permutation()**.

Shuffle

1. [Link to **numpy.random.shuffle**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html)<br>
The random.shuffle() function modifies the sequence of elements in an array.<br> 
The examples below demonstrate this. Note that the shuffle function only resequences the array in the first axis of a multidimensional array, i.e. it will shuffle the sequence of the arrays but not their contents.

In [8]:
# Generate a simple array of 10 integers. Note the  array is in numerical sequence.
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Now shuffle the array, contents remain the same but the sequence is randomly shuffled. 
np.random.shuffle(arr1)
arr1

array([0, 9, 8, 5, 1, 4, 6, 7, 3, 2])

In [10]:
# In a multidimensional array the array levels are shuffled and not the individual integers in each dimension.
# Generate a 6x3 array, note all in sequence.
arr2 = np.arange(18).reshape((6,3))
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [11]:
#Shuffle the array, note only the sequence of the sub arrays is shuffled and not the integers in each of the arrays. 
np.random.shuffle(arr2)
arr2

array([[ 0,  1,  2],
       [15, 16, 17],
       [ 9, 10, 11],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [12, 13, 14]])

Permutations

2. [Link to **numpy.random.permutation**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.permutation.html)<br>
Like the shuffle function the permutation function rearranges the elements of an array, along one axis only. The difference between this and the shuffle method is that the permutation leaves the original array unchanged and shuffles a copy of the array whereas shuffle changes the original array.

In [12]:
# Generate a 1D array and run the permutation method.
arr3 = np.arange(20)

In [13]:
random.permutation((arr3))

array([ 8,  5, 18,  6,  0,  1, 19, 16,  9, 12, 13,  3, 17,  7, 14, 15, 10,
       11,  4,  2])

In [14]:
# Generate a 5 x 5 array and run the permutation method
arr4 = np.arange(25).reshape((5,5))
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
# Like shuffle the permutation method only works on one axis, the subarrays are changed but not the integers in each one.
np.random.permutation(arr4)

array([[15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9]])

In [16]:
# Note the original array, arr4 is unchanged. 
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Section 3 - Exploration of Probability Distribution functions.

https://www.investopedia.com/terms/p/probabilitydistribution.asp<br>
https://www.analyticsvidhya.com/blog/2017/09/6-probability-distributions-data-science/
https://www.datacamp.com/community/tutorials/probability-distributions-python

Statistics and Probability are core elements of Data Science and are an essential part of data analysis. Machine learning and artificial learning make extensive use of distributions. At its most basic a probability distribution is a function that describes all of the possible values and probabilities that some random variable can have in a given range. 

In terms of random variables data can be either continuous or discrete.

- Continuous Data<br>
Continuous data is data that can take any value in a range. For example the ages, heights, weights of all the individuals in a school. 

- Discrete Data<br>
Discrete data is data that can only have specic values or outcomes, simplest example being when you roll a dice you can only get one of 6 values and the probablity of getting any one value is 1/6.

Probability Distrinutions<br>
For this section I have selected the following distributions for review:

- Normal
- Uniform
- Binomial
- Poisson
- Pareto
- Exponential


In [17]:
# For this section I am using the seaborn library for plotting examples of the distributions. 
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm

#### Normal Distribution

[Link to **numpy.random.normal**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html)

The Normal (or Gaussian) distribution is one of the most widely used and important distributions in statistical methods. It describes what very typically arises in nature where a huge number of random variations give rise to a normal range of outcomes. It is referred to as the Bell Curve as the plot of the distribution typically resembles the shape of a bell. In a normal distribution the mean, median, mode of the dataset are equal to each other and the curve is centered about the mean. Moving the mean moves the whole bell curve along the x axis. 

Many naturally ocurring phenonmena will fall into this type of distribution e.g.:
- Exam test scores
- Peoples Heights
- Quality control, range of errors in a production process.

The standard deviation is a measure of variability. It defines the width of the bell curve, i.e. how spread out the data is from the mean, the higher the standard deviation the wider the bell curve. It describes the typical distance between the data points and the average.

On a graph, changing the standard deviation either tightens or spreads out the width of the distribution along the X-axis. Larger standard deviations produce bell curves that spread out further.

The diagram below shows the characteristics of a Normal distribution
- The mean, mode, and median are all equal.
- The total area under the curve is equal to 1.
- The curve is symmetric around the mean.
- 68% of the data falls within one standard deviation of the mean.
- 95% of the data falls within two standard deviations of the mean.
- 99.7% of the data falls within three standard deviations of the mean.

![Example of a Bell Curve](https://www.askpython.com/wp-content/uploads/2020/10/Standard-deviation-around-mean.jpg.webp)

The code below produces a normal distribution of 1000 samples with a mean of 10 and a standard deviation of 3. It can be clearly seen how symettrical the output is with 10 in the center of the output. Increasing the number of samples brings the output closer to the perfect bell shape 

In [ ]:
samples = input("Enter number of samples:")
data = np.random.normal(loc=10, scale=3, size=int(samples))
sns.displot(data, kde=True)

#### Uniform Distribution
- A Uniform Distribution is used to describe probability of events in a range where each event has the same chance of occurring within a given range. Each event can be considered to be independant, e.g. tossing a coin. In numpy random this distribution takes 3 parameters, a lower bound (default 0), upper bound (default 1) and size, i.e. how many sampples are to be taken.  


In [21]:
# A simple example of a uniform distrinution is shown below.
values = np.random.uniform(0.0,1.0,10) 
sns.displot(values,bins=10,kde=True)

#### Binomial Distribution
A Binomial Distrinution is one where the outcome is binary, i.e. the toss of a coin, True, False, 1, 0. in numpy random the distribution takes 3 parameters, the number of trials, probability of success defined as p >=0 and p <=1 and the size of the arry to return.

In [22]:
#Example of a coin toss
sns.displot(random.binomial(n=10, p=0.5, size=1000),kde=True)

In [ ]:
#coin toss
s=np.random.binomial(12, 0.17, 200)
sns.displot(data=s, kde=True)

The differsnce between a normal distribution and a binomial distribution is that a normal distribution is continuous whereas a binmoial is descrete but given enough data points the outcome can be similar

In [ ]:
sns.displot(random.normal(loc=50, scale=5, size=1000),kde=True,label='normal')
sns.displot(random.binomial(n=100, p=0.5, size=1000),kde=True, label='binomial')

#### Poisson Distribution
A Poisson Distribution is a discrete probability distribution that can estimate the probability of how many times an event can happen in a specified time, the events being independant of each other, examples could be how many customer visits happen in an hour. It is a useful distribution where the average rate of events is known or can be estimated.  
numpy.random.poisson takes takes 2 parameters, **lam** being the mean rate of an occurrence in intervals of time or space and **size** being the number of returns in the array. 


In [ ]:
from scipy.stats import poisson
import matplotlib.pyplot as plt
#
# Random variable representing number of restaurants
# Mean number of occurences of restaurants in 10 KM is 2
#
X = [0, 1, 2, 3, 4, 5]
lmbda = 2
#
# Probability values
#
poisson_pd = poisson.pmf(X, lmbda)
#
# Plot the probability distribution
#
fig, ax = plt.subplots(1, 1, figsize=(8, 6))
ax.plot(X, poisson_pd, 'bo', ms=8, label='poisson pmf')
plt.ylabel("Probability", fontsize="18")
plt.xlabel("X - No. of Restaurants", fontsize="18")
plt.title("Poisson Distribution - No. of Restaurants Vs Probability", fontsize="18")
ax.vlines(X, 0, poisson_pd, colors='b', lw=5, alpha=0.5)

In [ ]:

sns.distplot(random.poisson(lam=2, size=1000), kde=False)

plt.show()

In [ ]:
x=np.random.poisson(5,20)
x

#### Pareto Distribution
Most people are familiar with the 80-20 rule, e.g. 80% of a companies revenue will be from 20% of its customers. 


In [ ]:
sns.distplot(random.pareto(a=2, size=1000), kde=False)

### Exponential Distribution
 An exponential distribution is used to estimate the time until the next event


In [ ]:
sns.displot(random.exponential(size=1000))

### Section 4 - Use of Seeds to Generate PseudoRandom Numbers.
As stated above pseudo-random numbers are not in fact true random numbers, in the context of numpy random they are computer generated numbers that are intended to appear random. A computer must follow a predetermined program or algorithim in order to generate these numbers and they use various techniques to produce random numbers that approximate true random numbers. 

One of the techniques used is the seed. In numpy the random function generates pseudo random numbers based on a seed. The seed is given some value and is used in the np.random.seed() function. 
Use of Seeds
- What are seeds
- why are they used
- what does numpy.random use as default
examples

In [ ]:
# Example of random seed to produce a simple array. Set the seed to 1. 
# No matter how many times this is run as long as the seed remains the same the "random" output will be the same. 
# While not very useful for randomness using the same seed number can be useful for debugging when you want to check something using the 
# same numbers each time. 
np.random.seed(1)
np.random.randint(0, 10, size = (10))

In [ ]:
# Changing the seed will change the output, in this case it is set to 2. 
# The output is different to the one above with seed(1)
# However note that running the code, as an example 10 times in this case, the output is the same each time. 
for i in range(10):
    np.random.seed(2)
    print(np.random.randint(0, 10, size = (10)))

In [ ]:
# What happens if there is no value of seed given. 
# What happens is that the seed uses a default value and that value is often generated using the computers system time as an element to generate
# a random seed number. 
# The code below produces a different output each time the code is executed. 
np.random.seed()
np.random.randint(0, 10, size = (10))

###### Some techniques to change the seed value. 
Clearly a fixed seed is of little proctical use outside of using for debugging, below are described with examples of some techniques to generate randon seed numbers. 

In [ ]:
# Use a random number as a seed, in this example using randint to generate a random number. 
# Note that a value from any random distribution can be used. 
for i in range(10):
    seed_number=np.random.randint(0,100)
    print("seed number: ",seed_number)
    np.random.seed(seed_number)
    print(np.random.randint(0, 10, size = 10))

In [ ]:
# Dont specify any seed, in this example the default seed() is used and each time the code runs a new randon seed is generated. 
for i in range(10):
    np.random.seed()
    print(np.random.randint(0, 10, size = 10))

In [ ]:
# Dont specify any seed, in this example the default seed() is used and each time the code runs a new randon seed is generated. 
import datetime
seed = int(time.time())
np.random.seed(seed)
print('Seed Time is: ',seed)
print(np.random.randint(0, 10, size = 10))

In [ ]:
# Random Shuffle is another method to produce a random output, 

In [ ]:
arr = np.arange(16).reshape((4,4))
np.random.shuffle(arr)
arr

## Websites

## References